name: Release And Deploy to Railway

on:
  push:
    branches: 
      - 'v[0-9]+\.[0-9]+'

jobs:
  Build:
    if: "!contains(github.event.head_commit.message, '#NOTRUN')"
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ğŸ€„
        uses: actions/checkout@v3
      - name: Create Release ğŸŒ¼
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          title: MyReleaseMessage

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ğŸ›°ï¸
        uses: actions/checkout@v3

      - name: Install Railway ğŸ¥³
        run: npm i -g @railway/cli

      - name: Deploy ğŸ˜†
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  
