name: Release And Deploy to Railway

on:
  push:
    branches: 
      - '/^v[0-9]+\.[0-9]+$/gmi'

jobs:
  Build:
    if: "!contains(github.event.head_commit.message, '#NOTRUN')"
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 0ï¸âƒ£
        uses: actions/checkout@v2
      - name: Create Release ğŸŒ¼
        id: create_release 
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.head_ref }}
          release_name: Release ${{ github.head_ref }}
          body: |
            Changes in this Release
              - First Change
              - Second Change
          draft: false
          prerelease: false

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ğŸ›°ï¸
        uses: actions/checkout@v3

      - name: Install Railway ğŸ¥³
        run: npm i -g @railway/cli

      - name: Deploy ğŸ˜†
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  
