name: Deploy to Railway And Release 

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code ğŸ›°ï¸
        uses: actions/checkout@v3

      - name: Install Railway ğŸ¥³
        run: npm i -g @railway/cli

      - name: Deploy ğŸ˜†
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

  Release:
      runs-on: ubuntu-latest
      permissions:
        contents: write
    
      steps:
      - uses: actions/checkout@v3
      - name: Create Release ğŸ“²
        uses: ncipollo/release-action@v1.11.1
        with: 
          token: ${{ secrets.GH_TOKEN }}
